#!/bin/bash

set -e

BASE_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/..
HADOOP_DIR=/usr/local/hadoop
CLASSES=(HdfsCacheReader HdfsReader HdfsWriter)
FILESIZES=(1g)

for c in ${CLASSES[@]}; do
for f in ${FILESIZES[@]}; do
$HADOOP_DIR/bin/hadoop jar hdfs_test.jar $c $f
printf -v out "%s %s done\n" "$c" "$f"
echo $out
done
done