#!/bin/bash

set -e

if [ $# -ne 4 ]
then
echo "Usage:$0 [tachyon host] [fileName] [writeType] [fileSize in G]"
cat << EOF 
	WriteType:
 	MUST_CACHE: Write the file and must cache it.
  	TRY_CACHE: Write the file and try to cache it.
  	CACHE_THROUGH: Write the file synchronously to the under fs, and also try to cache it,
  	THROUGH: Write the file synchronously to the under fs, no cache.
  	ASYNC_THROUGH: Write the file asynchronously to the under fs (either must cache or must through).
EOF
exit
fi

BASE_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/..

TACHYON_JAR=$BASE_DIR/localRepo/org/tachyonproject/tachyon/0.7.0-SNAPSHOT-jar-with-dependencies/tachyon-0.7.0-SNAPSHOT-jar-with-dependencies.jar

host=$1
fname=$2
writetype=$3
size=$4

echo "
java -cp $TACHYON_JAR:$BASE_DIR/target/pdct-testing-1.0.jar SingleFileTester tachyon://$host:19998 /$2 $3 $4
"
java -cp $TACHYON_JAR:$BASE_DIR/target/pdct-testing-1.0.jar SingleFileTester tachyon://$host:19998 /$2 $3 $4
